# Databricks notebook source
ID_COL = 'epma_id'
ORIGINAL_TEXT_COL = 'original_epma_description'
TEXT_COL = 'epma_description'
FORM_IN_TEXT_COL = 'form_in_text'
TEXT_WITHOUT_FORM_COL = 'epma_description_without_form'
MATCH_ID_COL = 'match_id'
MATCH_TERM_COL = 'match_term'
ID_LEVEL_COL = 'id_level'
MATCH_LEVEL_COL = 'match_level'
MATCH_DATETIME_COL = 'match_datetime'
REASON_COL = 'reason'
RUN_ID_COL = 'run_id'
VERSION_ID_COL = 'version_id'